modules:
  # Input Image '28x28x1' = 784x1
  Linear:
    shape=(784,64)
    name=linear1
  Relu:
    name=relu1

  Linear:
    (64,64)
    name=linear2
  Relu:
    name=relu2

  Linear:
    (64,10)
    name=output
  Softmax:

  CategoricalCrossEntropy:
      

